[build.environment]
    NODE_VERSION = "20"
[functions]
  external_node_modules = ["express", "mongoose"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"