[build.environment]
    NODE_VERSION = "20"
[functions]
  external_node_modules = ["express", "bcrypt", "config", "cors", "express-async-errors", "fawn", "joi-objectid", "jsonwebtoken", "moment", "mongoose", "winston", "winston-mongodb", "serverless-http"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"